[package]
name = "cofutures-macro"
version = "0.1.0"
authors = ["Stefan Bühler <stbuehler@web.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.26", features = [ "extra-traits", "full" ] }
quote = "0.6.10"
proc-macro2 = "0.4.25"
